### ISSUE TITLE
Reduxify 及相关重构 TODO

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#1078]
### 本体
- [ ] TopAlert
- [ ] 入渠
- [ ] 任务
- [ ] 部分通知系统（以及所有通知的 canNotify）
 - [x] 入渠通知确认工作
 - [ ] 建造通知确认不工作

### 插件重构
-  [ ] $ 和 _ 的 getter/setter
- _（请填入插件列表）_

## 需检查是否工作
- [ ] 各提示（都重构到 services 里了）
 - [ ] 开发提示
 - [x] 出击空位检查
 - [ ] 出击大破检查

## 计划的变动
- [ ] eslint
- [ ] cs -> es/js
- [ ] underscore -> lodash
- [ ] config 进入 redux
- [ ] battleenv 进入 redux
- [ ] reducer 深度判等

**Comment by dkwingsmt** [comment]
最新进展见 #1100
