### ISSUE TITLE
Reduxify 剩下的工作

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/poi#1100]
# 本体部分
## Todo
- [x] utils 分类：现在的工具函数主要散布在  `env/utils`、`redux/index`、`ship-parts` 及诸多其它文件中。除此之外，还有一些被重复使用的小模块（比如`ship-parts`中的多个模块）。需要规整到合适的地方，并且尽量使用 import 而不是全局函数。
- [x] quests 向后兼容性：quests 的记录文件现在不会记录该任务总进度（因为只是分进度之和），但这会导致切回老版本显示错误。@dkwingsmt
- [x] 包括 topalert 在内的各通知的 window.\* 应改为从 connect store 拿
- [x] 把奇怪的名字纠正为英文名，比如 kdock -> construction
- [x] 建造通知好像还不能使用
- [x] 升级新版 rb
- [x] 在 store.sortie 中加入 mapHp 
- [x] 兼容秘书语音插件
## 潜在 bug
- [x] 任务在莫名时候清空。现在仍有观察到，但原因不明。
- [x] ships 中的 undefined 键。有一段时间没有重现了。
## 收尾工作
- [x] 全面检查将 underscore 替换成 lodash，并且改用 import 模式。#1076 #1077
# 插件部分
## Reduxify
- [x] poi-plugin-prophet
- [x] poi-plugin-expedition
- [x] poi-plugin-quest-info
- [x] poi-plugin-exp-calc
- [x] poi-plugin-hensei-nikki
- [x] poi-plugin-senka-calc
- [x] poi-plugin-map-hp
- [x] poi-plugin-secretary
- [ ] poi-plugin-almanac
- [ ] poi-plugin-akashic-records
- [ ] poi-plugin-battle-detail
- [x] poi-plugin-wheres-my-fuel-gone
- [x] poi-plugin-item-improvement
- [x] poi-plugin-ship-info
- [x] poi-plugin-item-info
- [ ] poi-plugin-k2badge
- [x] poi-plugin-new-window
- [ ] poi-plugin-report
- [ ] poi-plugin-kcwiki-report
- [x] poi-plugin-subtitle
- [x] poi-plugin-translator
## Feature
- [x] 舰娘信息反潜值。

**Comment by dkwingsmt** [comment]
测试

**Comment by ruiii** [comment]
map-hp 和 quest-info 是不是也可以勾上了

**Comment by KochiyaOcean** [comment]
确定的话自己勾下就好啦

**Comment by dkwingsmt** [comment]
现在除了插件之外的部分都勾上了。

**Comment by KagamiChan** [comment]
插件需要做 reduxify 的应该都做了

**Comment by yukixz** [comment]
@KagamiChan 我没有
