### ISSUE TITLE
poi NEXT version Issue tracker & Discussion

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1532]
## React 16
- dependency compatibility
  - [x] react-toastr: updated
  - [x] react-bootstrap: rb's dep. react-overlays already done, waiting for rb's next minor version
- [x] everything inside main poi should work
  + 42
- plugins should work
  + [x] Hensen nikki
  + [x] expedition
  + [x] where my fuels gone
- [x] `ComponentDidCatch` API usage in plugin wrapper
- remove some unnecessary containers for array of elements

## General tasks
- [x] dependency housecleaning #1610 
- [x] improve IPC(Inter-Plugin-Communication) module
- [ ] prevent using unsafe screenshot directory
- [ ] new modernization mechanism support #1593 
- [ ] add welcome modal max height, and move content to markdown

**Comment by KagamiChan** [comment]
Since the React 16 part is nearly completed, I think it is time to introduce some new features and breaking changes. My thoughts:

- add `const.$graphs` to store in form of indexified object, going to deprecate `const.$shipgraph` because it is an `Array` and in practice the `Object` form is more favorable.
- add `html2canvas^0.5` library, this helps in converting HTML Dom into canvas/image
- add flv image decoding library and an API to get certain image uri from local decoded files. This could be used in plugins
