### ISSUE TITLE
Fall event API change issue tracker

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#1621]
- [x] lib battle
- [x] prophet
- [x] battle detail plugin
- [x] store.sortie.escapedPos: escape API's numbering has not changed, and 7 ship fleet escape fixed
- [x] escapeStatusSelectorFactory
- [x] sortie dangerous check
- [x] report, (drop, ssci, etc)

**Comment by Gizeta** [comment]
api更新对汇报插件有影响吗？
比如这行 https://github.com/poooi/plugin-report/blob/master/index.es#L200

**Comment by yukixz** [comment]
@Gizeta 显然

**Comment by yukixz** [comment]
@Gizeta 我暂时不知道新的包长什么样子，这里应该怎么改？

**Comment by Gizeta** [comment]
@yukixz 噗。我也不知道新包是长什么样，我是看tg群里有战斗包下载看了看。
貌似敌舰开头的 -1 没了，不过敌舰是不是6船限定我就不知道了。
