### ISSUE TITLE
Poi 10.x TODO list

### ISSUE THREAD

**Issue by KagamiChan** [poooi/poi#2018]
## BREAKING change
- [ ] Legacy dependency cleanup
  + `i18n-2`
  + `create-react-class`
  + `coffee-react`
  + `react-file-dropzone`
  + `swf-extract`
- `react-redux` 6
  + `withRef` deprecated
- coffeescript auto compiling is removed

## pending features
- [x] shipping a default value for **poi's own config** that has higher priority than `config.get`'s 3rd argument
- [ ] multiple plugin tabs (?)
- [x] blueprint themes
- [x] fps locking flag https://github.com/poooi/poi/issues/1978#issuecomment-424199911
- [x] settings tab content rearrange
