### ISSUE TITLE
Roadmap @ 5.0.0

### ISSUE THREAD

**Issue by KochiyaOcean** [poooi/poi#574]
This is the roadmap of poi version 5.0.0.
### Plugin mechanics
  - [x] Replace submodule with npm
  - [x] Update / Install / Remove
  - [x] Mirror server selector
  - [x] Manually install option

### Notification
  - [x] Use bundled method sending notification on Windows >= 8
  - [x] Support custom sound option

### UI
  - [x] Support SVG icon
  - [x] Switch between old and new icons
  - [x] font-family Remove Heiti #554 

### Distribution
- [x] Automatically package win and linux #516
- [x] Translate cs -> js #533
- [x] Package in asar 
- [x] Automatically generate offline plugin archive

### Dependcies
  - [x] Update Electron to v0.35.2
  - [x] Update React to v0.14: 
   - [x] All plugin compatibility solved.
  - [x] Update others to latest version  
   - Except coffee-script (

### i18n
  - [ ] Translate everything
   - [x] Quests #518
   - [ ] About poi
   - [ ] Welcome
  - [x] Plugin i18n-2 compatibility
      - [x] poi-plugin-akashic-records
      - [x] poi-plugin-battle-detail
      - [x] poi-plugin-exp-calc
      - [x] poi-plugin-expedition
      - [x] poi-plugin-hensei-nikki
      - [x] poi-plugin-item-improvement
      - [x] poi-plugin-item-info
      - [x] poi-plugin-map-hp
      - [x] poi-plugin-new-window
      - [x] poi-plugin-prophet
      - [x] poi-plugin-quest-info
      - [x] poi-plugin-report
      - [x] poi-plugin-ship-info
      - [x] poi-plugin-senka-calc
      - [x] poi-plugin-almanac

### Features
  - [x] plugin-stat  #566
  - [x] DYK (in main poi) #466
  - [x] Modernization (in main poi) #291
  - [x] Suppressing update notification  #532
  - [x] 活动图在出击海域的名字显示甲乙丙 #555
  - [x] Better accessibility of language settings #575
  - [x] Add a setting ui for the hide/show shortcut #527

### Must-fix trivia
  -  [x] poooi/plugin-quest#13

### Other possible trivial issues (do not have to)
  - [ ] 把推送信息的舰队名改为舰队编号 #543
  - [x] 调整分辨率处增加“恢复原分辨率”按钮 #548
  - [ ] 添加“清理所有缓存”按钮 #535

**Comment by Apuru** [comment]
Any chance you guys got an english version? Or could add translations to the road map?

**Comment by dkwingsmt** [comment]
@Apuru Language can be switched in settings. English is certainly included.

**Comment by Apuru** [comment]
Where in settings? I'm not seeing it in 4.2.1 win64 versions.

**Comment by taroxd** [comment]
@Apuru 
设置 - 基本设置 - 语言 - 简体中文

**Comment by dkwingsmt** [comment]
I guess you will need to restart poi to enable some of the translations.


Btw, we try to translate as much as we can - especially we should have translated everything in the main program. But sometimes we cannot cover plugins.

**Comment by Apuru** [comment]
Ah, I see it but it doesn't translate everything. 

Stuff like 
- Quests
- Ship names
- Two plugins 

Poi is probably the best Kantai Collection viewer atm and it would be great to have everyone use it so it can better collect statistics. I think you guys could steal a lot of users from KCV since Poi is very similar to Yuyuvn's version before it was abandoned.

**Comment by dkwingsmt** [comment]
lol I appreciate your praise on behalf of the dev team.

Quests include a huge amount of texts (for quest requirements) which is somewhat beyond our ability. It is being discussed tho, since we understand quests in kc are sometimes really hard to understand.

Ship names are another case. In my point of view, it's hard to decide whether to use Romaji (English letters) or to use Kanji (Chinese characters): the former is better for English speakers to correspond to the ones used in the game, while the latter is easier for you to pronounce and remember.

**Comment by alvin-777** [comment]
#555 不是早做了吗？

**Comment by taroxd** [comment]
Why not update Electron to the latest version (or at least 0.35.2)？

**Comment by KochiyaOcean** [comment]
Just a typo lol

**Comment by c933103** [comment]
As according to earlier discussions, while there are lots of text needed to
be translate for quest and such, it is not the main problem here since
those translation are readily available on wiki and other places. The main
difficulty involved in translating ship name/quest/etc. to English would be
the amount of code need to be rewritten.
2015/11/29 16:41 "Tong Mu" <notifications@github.com>:

**Comment by magicae** [comment]
+ Add a setting ui for the hide/show shortcut

**Comment by KagamiChan** [comment]
In my opinion, apart from the code work, there remains a problem of translation maintaining. Since almost every game update could introduce new ships and quests, the translation should be reviewed and updated as per game update, and dev team is then forced to release new version at the same frequency.
So it is better to provide ship/quest translation as an optional plugin, which directly modifies internal variables (if this way can cover all cases) or overrides certain views

**Comment by Apuru** [comment]
Sorry for bumping the old thread but I agree with KagamiChan. If the plugin is created, the English community can help maintain the addon with additional translations. I'm not skilled enough to write such a plugin but if someone makes an example then I can help maintain it.

**Comment by taroxd** [comment]
https://github.com/poooi/plugin-translator

**Comment by Apuru** [comment]
Beautiful. How would you translate quests with that plugin?

**Comment by dkwingsmt** [comment]
I'm working on an extensible format for quest requirements. It looks like this (see the "requirements" term
```
  {
    "game_id": 117,
    "wiki_id": "A11",
    "category": 1,
    "type": 1,
    "name": "第２艦隊で空母機動部隊を編成せよ！",
    "detail": "第２艦隊に空母を配備して、空母機動部隊を編成せよ！",
    "condition": "编组空母/轻母/水母1只+驱逐2只, 限第2舰队",
    "reward_fuel": 100,
    "reward_bullet": 0,
    "reward_steel": 0,
    "reward_alum": 100,
    "reward_other": "高速建造材x2",
    "prerequisite": [215],
    "requirements": {
      "category": "compfleet",
      "detail": {
        "groups": [
          {"ship": ["空母", "轻母", "水母"], "amount": 1},
          {"ship": "驱逐", "amount": 2}
        ],
        "fleetid": 2
      }
    }
  },
```
So that only limited formats and keywords (ship names, ship categories) need translation and almost no extra effort on internationalization is needed when new quests are added to the game.

It's still in progress and I think it's only a matter of time (I have to translate all existing quests).

Well, even if it fails, we can still grab everything from wikia using scripts. (Actually that's how I grabbed translations of ship names, which look like this
```
{
  "長門": "Nagato",
  "陸奥": "Mutsu",
  "伊勢": "Ise",
  "日向": "Hyuuga",
  "雪風": "Yukikaze",
  "赤城": "Akagi",
  "加賀": "Kaga",
  "蒼龍": "Souryuu",
  "飛龍": "Hiryuu",
...
```

**Comment by Apuru** [comment]
Wow, thats brilliant!

**Comment by yukixz** [comment]
close?
